### ISSUE TITLE
redux-subspace-observable compatibility with redux-observable v1

### ISSUE THREAD

**Issue by psamusev** [ioof-holdings/redux-subspace#91] opened 2018-07-04 10:30 UTC
### Feature
Compatibility with [redux-observable v1](https://redux-observable.js.org/MIGRATION.html). Looks like it relates to https://github.com/ioof-holdings/redux-subspace/issues/87

**Comment by mpeyper** [comment] 2018-07-04 21:58
Hi @psamusev,

@evertbouw has previously looked into it as part of [#86](https://github.com/ioof-holdings/redux-subspace/pull/86#issue-182764237), but I have not released those changes yet (If I'm being honest, I actually forgot about it when my baby was born - I'll put together a release ASAP).

I'd be interested to know what is/isn't working with redux-observable v1 at the moment.

**Comment by psamusev** [comment] 2018-07-05 07:48
Hi, @mpeyper. 

> I'd be interested to know what is/isn't working with redux-observable v1 at the moment.

I would say it mostly relates to types changes and a bit arguments updating inside epic as well as using new rxjs v6.0

**Comment by majo44** [comment] 2018-07-05 09:04
Other change is the api of middleware factory:
previous:
```
const epicMiddleware = createEpicMiddleware(rootEpic);
const store = createStore(rootReducer, applyMiddleware(epicMiddleware));
```
now:
```
const epicMiddleware = createEpicMiddleware();
const store = createStore(rootReducer, applyMiddleware(epicMiddleware));
epicMiddleware.run(rootEpic);
```

**Comment by evertbouw** [comment] 2018-07-05 10:14
Since the epics now receive a state$ instead of the store, we'll need to find a way to create this observable from the subspace store
________________________________

**Comment by mpeyper** [comment] 2018-07-05 22:36
> Since the epics now receive a state$ instead of the store, we'll need to find a way to create this observable from the subspace store

How do they create is from the actual redux store? the subspaces aim to be completely replaceable with a redux store (although it [doesn't implement `Symbol.observable`](https://github.com/ioof-holdings/redux-subspace/pull/86#issuecomment-382855279)) so we can hopefully do the same.

Is anyone willing to put their hand up to take this on? I'm very short on free time at the moment (new baby) and don't know when I'll be able to get to it?  I've had a look over @evertbouw's changes and it's a long way there, so would make a great starting point.

**Comment by mpeyper** [comment] 2018-07-14 04:01
Hey @evertbouw,

The fix for that test doesn't look right.  I think it might have something to do with removing the `applyToRoot` wrapper from the middleware in `this commit](https://github.com/evertbouw/redux-subspace/commit/04404451e177b98fa7f8a0689c0a7ca09cf1a9a4) (the saga middleware [does it when exporting from the index](https://github.com/ioof-holdings/redux-subspace/blob/master/packages/redux-subspace-saga/src/index.js#L15), which I don't see you doing).  Other than it possibly being the cause of the test failure, I think it is still important the the epic middleware is only applied to the root store.

I'm also not sure about [this change](https://github.com/evertbouw/redux-subspace/blob/master/packages/redux-subspace-observable/src/observable/subspaced.js#L30) but it might just be my lack of understanding of what it is doing.  the `mapState` function can accepts 2 parameters, the state of the parent store and the the state of the root store.  On top of that, the subspace `getState()` has a bunch of stuff going on, including `wormholes` which would not show up directly from the `mapState` call.

Would this work?

```js
const subspacedState$ = new StateObservable(state$.pipe(map(() => subspacedStore.getState())), subspacedStore.getState())
```

i.e. throw away what you thing the state is, this is your new state.

**Comment by evertbouw** [comment] 2018-07-16 15:23
Ah I did not see that `applyToRoot` was used in subspace-saga. Added it back.

Using any operators on the state$ means it'll lose `.value`. I think we should keep it, so I followed your first suggestion.

That fixed one test, but I still don't have a proper way to solve the error handling test.

**Comment by evertbouw** [comment] 2018-07-18 14:19
Guess I should have tried to look at the errors thrown in the test earlier 🤦‍♂️ Couldn't see them earlier but it was an easy fix.

**Closed** 2018-07-25 23:34 UTC
Labels: help wanted, improvement, investigation required
